### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by ghost** [GaryChangCN/ShouMedia#10]
你好，同学。 我想加入这个项目，能留个联系方式吗

**Comment by GaryChangCN** [comment]
garychangcn@hotmail.com

**Comment by GaryChangCN** [comment]
我的微信TinyTin

发件人: a49666 <notifications@github.com<mailto:notifications@github.com>>
答复: GaryChangCN/ShouMedia <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: 2017年5月10日 星期三 00:01
至: GaryChangCN/ShouMedia <ShouMedia@noreply.github.com<mailto:ShouMedia@noreply.github.com>>
抄送: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
主题: [GaryChangCN/ShouMedia] 你好 (#10)


你好，同学。 我想加入这个项目，能留个联系方式吗

**Comment by GaryChangCN** [comment]
我微信TInyTin

发件人: a49666 <notifications@github.com<mailto:notifications@github.com>>
答复: GaryChangCN/ShouMedia <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: 2017年5月10日 星期三 00:01
至: GaryChangCN/ShouMedia <ShouMedia@noreply.github.com<mailto:ShouMedia@noreply.github.com>>
抄送: Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
主题: [GaryChangCN/ShouMedia] 你好 (#10)


你好，同学。 我想加入这个项目，能留个联系方式吗
